prefix=/usr

install:
	find ./bundle -type f -exec install -Dm 0755 {} $(DESTDIR)$(prefix)/share/krane/{} \;
	find ./bin -type f -exec sed -i 's_\.\./\.\./bundle_$(DESTDIR)$(prefix)/share/krane/bundle_g' {} \;
	find ./bin -type f -name 'krane*' -exec install -Dm 0755 {} $(DESTDIR)$(prefix)/{} \;

